### ISSUE TITLE
saml_backend - discovery_response  (404)

### ISSUE THREAD

**Issue by janul** [SUNET/SATOSA#140]
Hi,
I use default settings regarding saml backend:
          discovery_response:
          - [<base_url>/<name>/disco, 'urn:oasis:names:tc:SAML:profiles:SSO:idp-discovery-protocol']
however when DS redirects back to https://HOST/Saml2/disco&entityID=MY_IDP_EXISTING_IN_METADATA
satosa gives 404 (Couldn't find the page you asked for!)

When I just call https://HOST/Saml2/disco then I'm readirect to rp (redirect_uri) (obviously with authn err response)

**Comment by jkakavas** [comment]
Where did you get these default settings from?

Example settings are : 
```
discovery_response:
          - [<base_url>/<name>/disco, 'urn:oasis:names:tc:SAML:profiles:SSO:idp-discovery-protocol']
```
as can be seen [here](https://github.com/SUNET/SATOSA/blob/master/example/plugins/backends/saml2_backend.yaml.example)

**Comment by janul** [comment]
I have,      
     `- [ <base_url>/<name>/disco, 'urn:oasis:names:tc:SAML:profiles:SSO:idp-discovery-protocol']`
It was just pasted incorrectly

Thanks

**Comment by jkakavas** [comment]
Now I spotted it. Your DS returns a malformed URL for the redirect : 
```
https://HOST/Saml2/disco&entityID=MY_IDP_EXISTING_IN_METADATA
```

should be

```
https://HOST/Saml2/disco?entityID=MY_IDP_EXISTING_IN_METADATA
```

What are you using for DS ? We had a similar problem in the [Delos Federation WAYF](https://wayf.grnet.gr) and there was a bug in our DS implementation.

**Comment by janul** [comment]
you're absolutely right. thanks for spotting it.
