### ISSUE TITLE
Docker image broken

### ISSUE THREAD

**Issue by mrvanes** [SUNET/SATOSA#65]
I'd like to know how alive satosa is at the moment because The Docker image was built 4 months ago but when I try to run the image I get the following error:

/tmp/satosa/start.sh: line 30: make_satosa_saml_metadata.py: command not found

I'm surprised nobody has noticed?

I'm totally new to Docker, so I might have missed some obvious configuration or bootstrapping, but I'd expect the docs to fully cover the necessary work to run the image?

**Comment by johanlundberg** [comment]
We are working on setting up automatic Docker builds of the SATOSA repo so the image should keep current (and versioned releases).

The governance of the project has changed from its-dirg to SUNET so we will update the README with the correct image uri soon as it is there.

A current image using SATOSA 3.3.1 can be pulled from docker.sunet.se/sunet/docker-satosa in the mean time.

Keeping this issue open until we have fixed our problem.
