### ISSUE TITLE
Docs are missing discovery API explanation

### ISSUE THREAD

**Issue by mrvanes** [SUNET/SATOSA#68]
I found the answer in the code, but would have preferred to find it in the docs ;)

In short, for those looking for an answer: Discovery service should return to url in _return_ parameter and return param _entityID_ for the chosen entityID.

On a sidenote: in order to shortcut the discovery service in test environment I pointed the discovery service URL back to the disco_response endpoint (/Saml2/disco in example) containing a preselected entityID. However, the create_discovery_service_request itself adds an entityID param as well, so there is some contamination that could have been prevented by choosing another consumer parameter for return entityID. I solved it by returning and checking for _eID_. Also, pysaml2 has a bug for discovery service url's containing a querypart, which I already created here https://github.com/rohe/pysaml2/issues/402

**Comment by s-hal** [comment]
Here you have the specification for the SAML2 Discovery Service
Protocol http://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-idp-discovery.pdf.

**Comment by mrvanes** [comment]
Thx. I didn't know SAML specs had a strict opinion about the discovery protocol.
Adding the URL to the docs near the discovery section would help.
