### ISSUE TITLE
upgrade pysaml2 to latest release version 4.4.0

### ISSUE THREAD

**Issue by skoranda** [SUNET/SATOSA#70]
I would like to use SATOSA with pysaml2 version 4.4.0 to pick up an enhancement in that package that I requested. The enhancement was to add support for the isMemberOf attribute from the eduMember objectClass. See

https://github.com/rohe/pysaml2/commit/468ac3918f84269d65c628790a6e542b5ee12cd4

That enhancement has been included in pysaml2 version 4.4.0

**Comment by johanlundberg** [comment]
Bump pysaml2 version 4.2.0 -> 4.4.0.
