### ISSUE TITLE
satosa-saml-metadata chokes on cert pem file containing trailing newline in signing cert.

### ISSUE THREAD

**Issue by mrvanes** [SUNET/SATOSA#80]
While copying certificates around I accidentally created a (signing) certificate file that had a trailing newline after the ```-----END CERTIFICATE-----``` line and satosa-saml-metadata choked on validate_base64 for this cert: ```binascii.Error: Incorrect padding```. It turns out the base64 value contains the ```-----END CERTIFICATE-----``` part of the cert (I added debug code to validate_base64 to show val).

I tried fixing this by adding a .strip() to the read_file command in read_cert_from_file in sigver.py @734 but this didn't resolve the problem?

So, I'm glad I found the problem and was able to fix the cert, but I was not able to make read_cert_from_file a bit more resilient for end-user mistakes like this?

**Comment by jkakavas** [comment]
This bug should be filed against https://github.com/rohe/pysaml2 which is the SAML library that SATOSA uses ( and contains the sigver.py  - https://github.com/rohe/pysaml2/blob/master/src/saml2/sigver.py - file you mention ).

I'm closing this here but we will make sure it will get fixed in pysaml2
